# file: docker-compose.yaml
version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ms-delivery
      POSTGRES_USER: svadmin
      POSTGRES_PASSWORD: Qwerty123
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U svadmin" ]
      interval: 10s
      timeout: 10s
      retries: 5
  ms-delivery-api:
    build: .
    image: ms-delivery-api
    ports:
      - 8081:8081
    links:
      - postgres
    depends_on:
      - postgres