# file: docker-compose.yaml
version: "3.9"
services:
  zookeeper:
    image: arm64v8/zookeeper:3.7.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - marketplace-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - marketplace-network

  postgres-delivery:
    image: postgres:16
    environment:
      POSTGRES_DB: ms-delivery
      POSTGRES_USER: svadmin
      POSTGRES_PASSWORD: Qwerty123
    ports:
      - 5433:5432 # Map container's 5432 to host's 5433
    volumes:
      - postgres-delivery-data:/var/lib/postgresql/data # Persist data in a named volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ms-delivery -U svadmin"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - marketplace-network
  ms-delivery-api:
    build: .
    image: ms-delivery-api
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres-delivery:5432/ms-delivery
      POSTGRES_USER: svadmin
      POSTGRES_PASSWORD: Qwerty123
      KAFKA_URL: localhost:9092
    ports:
      - 8081:8081
    depends_on:
      - postgres-delivery
      - kafka
    networks:
      - marketplace-network

volumes:
  postgres-delivery-data: # Named volume for PostgreSQL data

networks:
  marketplace-network:
    external: true