# file: docker-compose.yaml
version: "3.9"
services:
  postgres-delivery:
    image: postgres:16
    environment:
      POSTGRES_DB: ms-delivery
      POSTGRES_USER: svadmin
      POSTGRES_PASSWORD: Qwerty123
    ports:
      - 5433:5432 # Map container's 5432 to host's 5433
    volumes:
      - postgres-delivery-data:/var/lib/postgresql/data # Persist data in a named volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ms-delivery -U svadmin"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - marketplace-network
  ms-delivery-api:
    build: .
    image: ms-delivery-api
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres-delivery:5432/ms-delivery
      POSTGRES_USER: svadmin
      POSTGRES_PASSWORD: Qwerty123
      KAFKA_URL: kafka:9092
    ports:
      - 8081:8081
    depends_on:
      - postgres-delivery
    networks:
      - marketplace-network

volumes:
  postgres-delivery-data: # Named volume for PostgreSQL data

networks:
  marketplace-network:
    external: true