server:
  port: 8081
  servlet:
    context-path: /ms-delivery

spring:
  application:
    name: ms_delivery
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb-delivery
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: marketplace.svysk
