server:
  port: 8081
  servlet:
    context-path: /ms-delivery

spring:
  application:
    name: ms_delivery
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb-delivery
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
